// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_live.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ3oHDK9OEQBVTMA6D7PIVpOm_nYBw7E4',
    appId: '1:488060032510:web:e766ea08b4b474f72d5caf',
    messagingSenderId: '488060032510',
    projectId: 'bla-app-live',
    authDomain: 'bla-app-live.firebaseapp.com',
    storageBucket: 'bla-app-live.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMablaM1NzBHmPDDMZBRqgtNS5K3Oir7M',
    appId: '1:488060032510:android:5ba8b3bead3ea7f02d5caf',
    messagingSenderId: '488060032510',
    projectId: 'bla-app-live',
    storageBucket: 'bla-app-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbFzTVnM41HkPigCywZhyPcC80sjD2vVc',
    appId: '1:488060032510:ios:175c9deba46077e42d5caf',
    messagingSenderId: '488060032510',
    projectId: 'bla-app-live',
    storageBucket: 'bla-app-live.firebasestorage.app',
    iosBundleId: 'com.example.blaFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbFzTVnM41HkPigCywZhyPcC80sjD2vVc',
    appId: '1:488060032510:ios:175c9deba46077e42d5caf',
    messagingSenderId: '488060032510',
    projectId: 'bla-app-live',
    storageBucket: 'bla-app-live.firebasestorage.app',
    iosBundleId: 'com.example.blaFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ3oHDK9OEQBVTMA6D7PIVpOm_nYBw7E4',
    appId: '1:488060032510:web:d5f8e1423cc210822d5caf',
    messagingSenderId: '488060032510',
    projectId: 'bla-app-live',
    authDomain: 'bla-app-live.firebaseapp.com',
    storageBucket: 'bla-app-live.firebasestorage.app',
  );
}
