// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbUvdWQL-FcwYRITlkif8tEdi8PPmU3tc',
    appId: '1:251739467545:web:d37bca8d12caa37e515f88',
    messagingSenderId: '251739467545',
    projectId: 'bla-app-staging',
    authDomain: 'bla-app-staging.firebaseapp.com',
    storageBucket: 'bla-app-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm03BmNEYMfDZbwJaxT2SeHH1_MO-HBvs',
    appId: '1:251739467545:android:d2cc5feb896d9626515f88',
    messagingSenderId: '251739467545',
    projectId: 'bla-app-staging',
    storageBucket: 'bla-app-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVVh0NNFSZGiCm5PeJgk4z6NaG5IPMjas',
    appId: '1:251739467545:ios:75987c32824e4c9d515f88',
    messagingSenderId: '251739467545',
    projectId: 'bla-app-staging',
    storageBucket: 'bla-app-staging.firebasestorage.app',
    iosBundleId: 'com.beaconlightacademy.app.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVVh0NNFSZGiCm5PeJgk4z6NaG5IPMjas',
    appId: '1:251739467545:ios:4792cb5394116226515f88',
    messagingSenderId: '251739467545',
    projectId: 'bla-app-staging',
    storageBucket: 'bla-app-staging.firebasestorage.app',
    iosBundleId: 'com.example.blaFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbUvdWQL-FcwYRITlkif8tEdi8PPmU3tc',
    appId: '1:251739467545:web:7a3d110e50f8b6e2515f88',
    messagingSenderId: '251739467545',
    projectId: 'bla-app-staging',
    authDomain: 'bla-app-staging.firebaseapp.com',
    storageBucket: 'bla-app-staging.firebasestorage.app',
  );

}